import { expect, type Page, type TestInfo } from '@playwright/test';

export async function htmlCommentJourney(page: Page, info: TestInfo) {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/demos/node-markdown.html');
  const input = page.getByLabel('Markdown input', { exact: true });
  await input.click();
  await page.keyboard.press('ControlOrMeta+a');
  await page.keyboard.type('Release <!-- provenance --> **notes**.');
  await expect(input).toHaveValue('Release <!-- provenance --> **notes**.');
  await expect(page.locator('.demo-output')).toContainText('provenance');
  await page.getByLabel('Convert HTML across the complete document', { exact: true }).check();
  await page.getByLabel('Preserve inert HTML comments', { exact: true }).check();
  const output = page.locator('.demo-output');
  await expect(output).toContainText('html_comment');
  await output.getByRole('button', { name: 'html', exact: true }).click();
  await expect(output.locator('pre')).toContainText('<!-- provenance -->');
  await page.getByLabel('Preserve inert HTML comments', { exact: true }).uncheck();
  await expect(page.getByLabel('Markdown HTML conversion details')).toContainText('An HTML comment was omitted');
  await page.getByLabel('Preserve inert HTML comments', { exact: true }).check();

  const workshop = page.getByRole('region', { name: 'HTML comment authoring workshop' });
  await workshop.scrollIntoViewIfNeeded();
  const editor = workshop.getByRole('textbox', { name: 'HTML comment authoring editor', exact: true });
  await expect(editor.locator('[data-fountain-html-comment]')).toHaveCount(1);
  await expect(editor.getByText('HTML comment', { exact: true })).toBeVisible();
  await page.evaluate(() => {
    document.querySelector('[aria-label="HTML comment authoring editor"]')!.addEventListener('copy', event => {
      const clipboard = (event as ClipboardEvent).clipboardData;
      (globalThis as any).__htmlCommentCopy = { plain: clipboard?.getData('text/plain'), html: clipboard?.getData('text/html') };
    }, { once: true });
  });
  await editor.locator('[data-fountain-html-comment]').click();
  await page.keyboard.press('ControlOrMeta+c');
  await expect.poll(() => page.evaluate(() => (globalThis as any).__htmlCommentCopy?.html)).toContain('<!-- provenance: imported draft -->');
  expect(await page.evaluate(() => (globalThis as any).__htmlCommentCopy?.plain)).toBe('');
  await page.keyboard.press('Backspace');
  await expect(editor.locator('[data-fountain-html-comment]')).toHaveCount(0);
  await expect(editor).toContainText('Release notes remain editable.');
  await page.keyboard.press('ControlOrMeta+z');
  await expect(editor.locator('[data-fountain-html-comment]')).toHaveCount(1);
  await workshop.getByRole('button', { name: 'Save comment Markdown and preview' }).click();
  const saved = workshop.getByLabel('Saved comment Markdown');
  const original = await saved.inputValue();
  await expect(workshop.getByRole('status')).toHaveText('Source preservation: exact');
  await expect(workshop.frameLocator('iframe[title="HTML comment reader snapshot"]').locator('body')).toContainText('Review the rollout.');
  await workshop.locator('iframe').scrollIntoViewIfNeeded();
  await workshop.frameLocator('iframe[title="HTML comment reader snapshot"]').locator('body').screenshot({ path: info.outputPath('comment-reader-original.png') });
  await workshop.screenshot({ path: info.outputPath('comment-author-original.png') });
  await editor.locator('p').last().click();
  await page.keyboard.press('End');
  await page.keyboard.type(' Reviewed.');
  await workshop.getByLabel('HTML comment data', { exact: true }).fill(' provenance: reviewed by Ada ');
  await workshop.getByRole('button', { name: 'Apply comment data' }).click();
  await expect(editor.locator('[data-fountain-html-comment]')).toHaveAttribute('title', 'HTML comment:  provenance: reviewed by Ada ');
  await workshop.getByRole('button', { name: 'Save comment Markdown and preview' }).click();
  await expect(saved).toContainText('<!-- provenance: reviewed by Ada -->');
  await expect(saved).toContainText('<strong>notes</strong>');
  await expect(saved).toContainText('Reviewed.');
  const reader = workshop.frameLocator('iframe[title="HTML comment reader snapshot"]');
  await expect(reader.locator('body')).toContainText('Release notes remain editable.');
  await expect(reader.locator('[data-fountain-html-comment]')).toHaveCount(0);
  await expect(reader.locator('script')).toHaveCount(0);
  await expect(reader.locator('html')).toHaveAttribute('lang', 'en');
  await expect(reader.locator('title')).toHaveJSProperty('textContent', 'HTML comment reader snapshot');
  await expect(reader.locator('main')).toHaveCount(1);
  await expect(workshop.locator('iframe')).toHaveAttribute('sandbox', '');
  await expect(reader.locator('body')).not.toContainText('provenance');
  const comments = await reader.locator('body').evaluate(body => {
    const walker = body.ownerDocument.createTreeWalker(body, 128);
    const result: string[] = []; while (walker.nextNode()) result.push(walker.currentNode.textContent ?? ''); return result;
  });
  expect(comments).toEqual([' provenance: reviewed by Ada ']);
  await workshop.locator('iframe').scrollIntoViewIfNeeded();
  await reader.locator('body').screenshot({ path: info.outputPath('comment-reader-edited.png') });
  await workshop.screenshot({ path: info.outputPath('comment-author-edited-and-reader.png') });
  await workshop.getByLabel('HTML comment data', { exact: true }).fill('break --> <script>bad()</script>');
  await workshop.getByRole('button', { name: 'Apply comment data' }).click();
  await expect(workshop.getByRole('status')).toContainText('No change:');
  await expect(editor.locator('[data-fountain-html-comment]')).toHaveAttribute('title', 'HTML comment:  provenance: reviewed by Ada ');
  await workshop.getByRole('button', { name: 'Undo comment edit', exact: true }).click();
  await expect(workshop.getByLabel('HTML comment data', { exact: true })).toHaveValue(' provenance: imported draft ');
  await workshop.getByRole('button', { name: 'Undo comment edit', exact: true }).click();
  await workshop.getByRole('button', { name: 'Save comment Markdown and preview' }).click();
  await expect(saved).toHaveValue(original);
  await workshop.getByRole('button', { name: 'Remove HTML comment', exact: true }).click();
  await expect(editor.locator('[data-fountain-html-comment]')).toHaveCount(0);
  await expect(editor).toContainText('Release notes remain editable.');
  await workshop.getByRole('button', { name: 'Undo comment edit', exact: true }).click();
  await expect(editor.locator('[data-fountain-html-comment]')).toHaveCount(1);
  await workshop.getByRole('button', { name: 'Save comment Markdown and preview' }).click();
  await expect(saved).toHaveValue(original);
  await page.setViewportSize({ width: 390, height: 844 });
  await workshop.getByLabel('HTML comment data', { exact: true }).scrollIntoViewIfNeeded();
  await expect(workshop.getByRole('button', { name: 'Apply comment data' })).toBeVisible();
  await workshop.screenshot({ path: info.outputPath('comment-author-mobile.png') });
  await workshop.locator('iframe').scrollIntoViewIfNeeded();
  await reader.locator('body').screenshot({ path: info.outputPath('comment-reader-mobile.png') });
  expect(errors).toEqual([]);
}
