import { expect, type Page, type TestInfo } from '@playwright/test';
import { inStableDocument } from './stable-document';

export async function markdownParagraphRecoveryJourney(page: Page, info: TestInfo): Promise<void> {
  const capture = async (name: string) => {
    await page.evaluate(async () => { await document.fonts.ready; window.scrollTo({ top: 0, behavior: 'instant' }); await new Promise<void>(resolve => requestAnimationFrame(() => requestAnimationFrame(() => resolve()))); });
    await page.screenshot({ path: info.outputPath(name), fullPage: true });
  };
  const replaceByPaste = async (html: string) => inStableDocument(page, 'Select all and paste converted HTML', async () => {
    const surface = page.getByRole('textbox', { name: 'Issue description editor', exact: true });
    await surface.click();
    await page.keyboard.press('ControlOrMeta+a');
    // Public paste event payload, not OS clipboard permission certification.
    await surface.evaluate((element, value) => {
      const event = new Event('paste', { bubbles: true, cancelable: true });
      Object.defineProperty(event, 'clipboardData', { value: { files: [], getData: (type: string) => type === 'text/html' ? value : '' } });
      element.dispatchEvent(event);
    }, html);
  });
  await page.goto('/demos/node-markdown.html');
  const source = page.getByLabel('Markdown input', { exact: true });
  await source.fill('Before <h2>Recovered heading</h2> After');
  const output = page.locator('.demo-output');
  await output.getByRole('button', { name: 'html', exact: true }).click();
  await expect(output.locator('pre')).toContainText('&lt;h2&gt;');
  await page.getByRole('checkbox', { name: 'Recover block tags inside paragraphs' }).check();
  await expect(output.locator('pre')).toContainText('<h2>Recovered heading</h2>');
  const html = await output.locator('pre').innerText();
  await source.fill('Before <script>literal</script> After');
  await expect(page.getByRole('list', { name: 'Markdown HTML conversion details' })).toContainText('Kept paragraph HTML as text');
  await expect(output.locator('pre')).toContainText('&lt;script&gt;');
  await page.goto('/issue-editor.html');
  const editor = page.getByRole('textbox', { name: 'Issue description editor', exact: true });
  await replaceByPaste(html);
  const verify = async (surface: typeof editor) => {
    await expect(surface.locator('h2')).toHaveText('Recovered heading');
    await expect(surface.locator('p')).toHaveText(['Before', 'After', '']);
    const before = await surface.locator('p').first().boundingBox();
    const heading = await surface.locator('h2').boundingBox();
    const after = await surface.locator('p').nth(1).boundingBox();
    expect(heading!.y).toBeGreaterThanOrEqual(before!.y + before!.height);
    expect(after!.y).toBeGreaterThanOrEqual(heading!.y + heading!.height);
  };
  await verify(editor);
  await editor.getByText('After', { exact: true }).click();
  await page.keyboard.press('End');
  await page.keyboard.type(' updated');
  await expect(editor).toContainText('After updated');
  await page.keyboard.press('ControlOrMeta+z');
  await verify(editor);
  await capture('recovered-paragraph-editor.png');
  const pending = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Download Markdown draft', exact: true }).click();
  const path = info.outputPath('recovered-paragraph.md');
  await (await pending).saveAs(path);
  await page.getByLabel('Open Markdown draft file', { exact: true }).setInputFiles(path);
  await verify(editor);
  await page.getByRole('button', { name: 'Reader preview', exact: true }).click();
  const reader = page.getByRole('textbox', { name: 'Issue preview', exact: true });
  await verify(reader);
  await capture('recovered-paragraph-reader.png');
  await page.setViewportSize({ width: 390, height: 844 });
  await verify(reader);
  await capture('recovered-paragraph-mobile.png');
  await page.setViewportSize({ width: 1440, height: 960 });
  await page.goto('/demos/node-markdown.html');
  await source.fill('- Before <h2>Recovered list heading</h2> After\n- Second item');
  await output.getByRole('button', { name: 'html', exact: true }).click();
  await page.getByRole('checkbox', { name: 'Recover block tags inside paragraphs' }).check();
  await expect(output.locator('pre')).toContainText('<h2>Recovered list heading</h2>');
  const listHTML = await output.locator('pre').innerText();
  await source.fill('- Before <h2>Recovered list heading</h2> After\n\n- Second item');
  await expect(output.locator('pre')).toContainText('<p></p>');
  await page.goto('/issue-editor.html');
  await replaceByPaste(listHTML);
  const verifyList = async (surface: typeof editor) => {
    await expect(surface.locator('li')).toHaveCount(2);
    await expect(surface.locator('li').first().locator('p')).toHaveText(['Before', 'After']);
    await expect(surface.locator('li').first().locator('h2')).toHaveText('Recovered list heading');
    await expect(surface.locator('li').nth(1)).toHaveText('Second item');
  };
  await verifyList(editor);
  await editor.getByText('After', { exact: true }).click();
  await page.keyboard.press('End');
  await page.keyboard.type(' edited');
  await expect(editor).toContainText('After edited');
  await page.keyboard.press('ControlOrMeta+z');
  await verifyList(editor);
  await capture('tight-list-editor.png');
  const listDownload = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Download Markdown draft', exact: true }).click();
  const listPath = info.outputPath('tight-list.md');
  await (await listDownload).saveAs(listPath);
  await page.getByLabel('Open Markdown draft file', { exact: true }).setInputFiles(listPath);
  await verifyList(editor);
  await page.getByRole('button', { name: 'Reader preview', exact: true }).click();
  await verifyList(reader);
  await capture('tight-list-reader.png');
  await page.setViewportSize({ width: 390, height: 844 });
  await verifyList(reader);
  await capture('tight-list-mobile.png');
  await page.setViewportSize({ width: 1440, height: 960 });
  await page.goto('/demos/node-markdown.html');
  await source.fill('Before <pre>&#13;\nfirst line&#13;\n  second line\nlast line</pre> After');
  await output.getByRole('button', { name: 'html', exact: true }).click();
  await page.getByRole('checkbox', { name: 'Recover block tags inside paragraphs' }).check();
  await expect(output.locator('pre')).toContainText('first line\n  second line\nlast line');
  await expect(page.getByRole('list', { name: 'Markdown HTML conversion details' })).toContainText('Preformatted HTML became a code block');
  const preHTML = await output.locator('pre').innerText();
  await page.goto('/issue-editor.html');
  await replaceByPaste(preHTML);
  const verifyPre = async (surface: typeof editor) => {
    // String-based toHaveText normalizes whitespace and would miss collapsed LF
    // or indentation. Compare raw text and the actual whitespace rendering mode.
    await expect.poll(() => surface.locator('pre').textContent()).toBe('first line\n  second line\nlast line');
    expect(await surface.locator('pre').evaluate(element => getComputedStyle(element).whiteSpace)).toMatch(/^(pre|pre-wrap|break-spaces)$/);
    await expect(surface.locator('p')).toHaveText(['Before', 'After', '']);
  };
  await verifyPre(editor);
  await editor.locator('pre').click();
  await page.keyboard.press('End');
  await page.keyboard.type(' edited');
  await expect(editor.locator('pre')).toContainText(' edited');
  await page.keyboard.press('ControlOrMeta+z');
  await verifyPre(editor);
  await capture('preformatted-editor.png');
  const preDownload = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Download Markdown draft', exact: true }).click();
  const prePath = info.outputPath('preformatted.md');
  await (await preDownload).saveAs(prePath);
  await page.getByLabel('Open Markdown draft file', { exact: true }).setInputFiles(prePath);
  await verifyPre(editor);
  await page.getByRole('button', { name: 'Reader preview', exact: true }).click();
  await verifyPre(reader);
  await capture('preformatted-reader.png');
  await page.setViewportSize({ width: 390, height: 844 });
  await verifyPre(reader);
  await capture('preformatted-mobile.png');
}
