import { expect, type Page, type TestInfo } from '@playwright/test';
import { mathReferenceSamples } from '../../examples/react-app/src/math-reference-samples';

export async function mathReferencesJourney(page: Page, info: TestInfo) {
  const errors: string[] = [];
  const external: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('request', request => { if (!['127.0.0.1', 'localhost'].includes(new URL(request.url()).hostname)) external.push(request.url()); });
  await page.goto('/math-references.html');
  const licenses = await page.request.get('/mathjax-notices.txt');
  expect(licenses.ok()).toBe(true);
  expect(await licenses.text()).toContain('SIL OPEN FONT LICENSE Version 1.1');
  const author = page.getByRole('textbox', { name: 'Equation author editor', exact: true });
  const reader = page.getByRole('textbox', { name: 'Equation reader preview', exact: true });
  const blocks = author.locator('[data-fountain-math="block"]');
  const references = author.locator('[data-fountain-math="inline"] [data-document-mathjax]');
  await expect(author.locator('mjx-container > svg')).toHaveCount(4);
  await expect(reader.locator('mjx-container > svg')).toHaveCount(4);
  await expect(page.getByRole('status')).toContainText('References resolved');
  await expect(blocks.nth(0)).toHaveAttribute('data-latex', mathReferenceSamples[1].source);
  await expect(blocks.nth(1)).toHaveAttribute('data-latex', mathReferenceSamples[2].source);
  await author.screenshot({ path: info.outputPath('01-published-equations-author.png') });
  await expect(reader.locator('p').first()).toContainText('The deterministic model');
  const readerGeometry = await reader.evaluate(root => {
    const bounds = root.getBoundingClientRect();
    return { height: bounds.height, scrollTop: root.scrollTop, children: [...root.children].map(child => {
      const rect = child.getBoundingClientRect();
      return { type: child.getAttribute('data-fountain-node'), top: rect.top - bounds.top, bottom: rect.bottom - bounds.top };
    }) };
  });
  expect(readerGeometry.children.every(child => child.top >= 0 && child.bottom <= readerGeometry.height)).toBe(true);
  await info.attach('reader-geometry', { body: JSON.stringify(readerGeometry), contentType: 'application/json' });
  await page.getByRole('region', { name: 'Equation reading' }).screenshot({ path: info.outputPath('02-published-equations-reader.png') });
  const link = reader.locator('a').first();
  const href = await link.getAttribute('href');
  expect(href).toMatch(/^#fountain-mjx-/);
  await link.click();
  await expect(page).toHaveURL(new RegExp(href!.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '$'));
  await expect(reader.locator('textarea:visible')).toHaveCount(0);
  const readerBefore = await reader.textContent();
  await reader.locator('p').first().click();
  await page.keyboard.type('READONLY_CHECK');
  expect(await reader.textContent()).toBe(readerBefore);

  await blocks.nth(1).hover();
  await page.getByRole('toolbar', { name: /Math block controls/i }).getByRole('button', { name: /Move Math block before/i }).click();
  await expect(references.nth(0)).toHaveAttribute('data-equation-references', '(2)');
  await expect(references.nth(1)).toHaveAttribute('data-equation-references', '(1)');
  await expect(reader.locator('[data-fountain-math="inline"] [data-document-mathjax]').first()).toHaveAttribute('data-equation-references', '(2)');
  await blocks.first().locator('.fountain-math__output').click();
  const source = blocks.first().getByLabel('Edit math source', { exact: true });
  await expect(source).toHaveValue(mathReferenceSamples[2].source);
  await source.focus();
  await source.press('Control+Home');
  await source.press('ArrowDown');
  await source.press('Home');
  for (let i = 0; i < 4; i++) await source.press('ArrowRight');
  for (let i = 0; i < 6; i++) await source.press('Shift+ArrowRight');
  await page.keyboard.type('\\beta');
  await expect(source).toHaveValue(mathReferenceSamples[2].source.replace('\\alpha', '\\beta'));
  await expect(author.locator('mjx-container > svg')).toHaveCount(4);
  await expect(page.getByRole('status')).toContainText('References resolved');
  await source.press('Control+Enter');
  await author.screenshot({ path: info.outputPath('03-reordered-edited-equations.png') });
  await page.getByRole('button', { name: 'Undo', exact: true }).click();
  await expect(blocks.first()).toHaveAttribute('data-latex', mathReferenceSamples[2].source);
  await blocks.first().locator('.fountain-math__output').click();
  await page.getByRole('button', { name: 'Delete selected formula' }).click();
  await expect(blocks).toHaveCount(1);
  await expect(page.getByRole('status')).toContainText('Unresolved equation reference');
  await expect(references.nth(1)).toHaveAttribute('data-equation-references', '(???)');
  await expect(reader.locator('[data-fountain-math="inline"] [data-document-mathjax]').nth(1)).toHaveAttribute('data-equation-references', '(???)');
  await author.screenshot({ path: info.outputPath('04-deleted-target-unresolved.png') });
  await page.getByRole('button', { name: 'Undo', exact: true }).click();
  await expect(page.getByRole('status')).toContainText('References resolved');
  await blocks.first().locator('.fountain-math__output').click();
  await source.fill(mathReferenceSamples[1].source);
  await expect(page.getByRole('status')).toContainText('multiply defined');
  await expect(author.locator('svg')).toHaveCount(0);
  await expect(reader.locator('svg')).toHaveCount(0);
  await author.screenshot({ path: info.outputPath('05-duplicate-label-source-fallback.png') });
  await page.getByRole('button', { name: 'Restore published equations' }).click();
  await expect(page.getByRole('status')).toContainText('References resolved');
  await page.getByRole('button', { name: 'Add equation', exact: true }).click();
  await expect(blocks).toHaveCount(3);
  await expect(blocks.last().locator('[data-document-mathjax]')).toHaveAttribute('data-equation-tags', '(3)');
  await page.getByRole('button', { name: 'Delete selected formula' }).click();
  await expect(blocks).toHaveCount(2);
  await page.getByText('Markdown source export', { exact: true }).click();
  const exported = page.locator('details').last().locator('pre');
  await expect(exported).toContainText(mathReferenceSamples[1].source);
  await expect(exported).toContainText(mathReferenceSamples[2].source);
  await expect(exported).toContainText('\\eqref{eq:dNFE}');
  await page.setViewportSize({ width: 390, height: 844 });
  await author.scrollIntoViewIfNeeded();
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
  const output = blocks.first().locator('.fountain-math__output');
  expect(await output.evaluate(element => element.scrollWidth > element.clientWidth)).toBe(true);
  await author.screenshot({ path: info.outputPath('06-narrow-scrollable-equations.png') });
  await output.hover();
  await page.mouse.wheel(1200, 0);
  await expect.poll(() => output.evaluate(element => element.scrollLeft)).toBeGreaterThan(100);
  // Preserve the caret: hiding it makes Playwright mutate contenteditable
  // styles, which can cause the editor's DOM repair to replace nested targets.
  await output.screenshot({ path: info.outputPath('07-narrow-equation-scrolled-to-number.png'), caret: 'initial' });
  expect(errors).toEqual([]);
  expect(external).toEqual([]);
}
