import { expect, type Page, type TestInfo } from '@playwright/test';
import { readFile } from 'node:fs/promises';

export async function mathFilesJourney(page: Page, info: TestInfo) {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/math-references.html');
  const author = page.getByRole('textbox', { name: 'Equation author editor', exact: true });
  const reader = page.getByRole('textbox', { name: 'Equation reader preview', exact: true });
  const blocks = author.locator('[data-fountain-math="block"]');
  const json = page.locator('details').first().locator('pre');
  const jsonValue = async () => JSON.parse((await json.textContent())!);
  const initial = await jsonValue();
  await page.getByRole('button', { name: 'Add equation', exact: true }).click();
  await expect(blocks).toHaveCount(3);
  await blocks.nth(1).hover();
  await page.getByRole('toolbar', { name: /Math block controls/i }).getByRole('button', { name: /Move Math block before/i }).click();
  await expect(author.locator('[data-fountain-math="inline"] [data-equation-references]').first()).toHaveAttribute('data-equation-references', '(2)');
  let saved = await jsonValue();
  const downloadEvent = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Save JSON', exact: true }).click();
  const download = await downloadEvent;
  expect(download.suggestedFilename()).toBe('equations.fountain.json');
  const path = info.outputPath('equations.fountain.json');
  await download.saveAs(path);
  const bytes = await readFile(path);
  expect(JSON.parse(bytes.toString('utf8'))).toEqual(saved);
  expect(bytes.toString('utf8')).not.toMatch(/fountain-mjx-|<svg|data-equation-tags/);

  // Destroy both views by reloading: this is not merely undoing in one instance.
  await page.reload();
  await expect(blocks).toHaveCount(2);
  const file = page.getByLabel('Open Fountain document JSON', { exact: true });
  await file.setInputFiles(path);
  await expect(page.locator('[data-file-message]')).toContainText('Opened equations.fountain.json');
  expect(await jsonValue()).toEqual(saved);
  await expect(reader.locator('[data-fountain-math="block"]')).toHaveCount(3);
  await expect(page.getByRole('status')).toContainText('References resolved');
  await expect(author.locator('[data-fountain-math="inline"] [data-equation-references]').first()).toHaveAttribute('data-equation-references', '(2)');
  await page.getByRole('button', { name: 'Undo', exact: true }).click();
  expect(await jsonValue()).toEqual(initial);
  await page.getByRole('button', { name: 'Redo', exact: true }).click();
  expect(await jsonValue()).toEqual(saved);
  // Simulate a document supplied by a host that stores root-level metadata.
  saved = { ...saved, attrs: { paperTitle: 'Retained across files', source: { revision: 7 } } };
  await file.setInputFiles({ name: 'metadata.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(saved)) });
  await expect(page.locator('[data-file-message]')).toContainText('Opened metadata.json');
  expect(await jsonValue()).toEqual(saved);
  const metadataEvent = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Save JSON', exact: true }).click();
  const metadataDownload = await metadataEvent;
  const metadataPath = info.outputPath('metadata.fountain.json');
  await metadataDownload.saveAs(metadataPath);
  expect(JSON.parse(await readFile(metadataPath, 'utf8'))).toEqual(saved);
  await page.reload();
  await expect(blocks).toHaveCount(2);
  await file.setInputFiles(metadataPath);
  await expect(page.locator('[data-file-message]')).toContainText('Opened metadata.fountain.json');
  expect(await jsonValue()).toEqual(saved);
  await page.getByRole('button', { name: 'Undo', exact: true }).click();
  expect(await jsonValue()).toEqual(initial);
  await page.getByRole('button', { name: 'Redo', exact: true }).click();
  expect(await jsonValue()).toEqual(saved);
  await page.getByRole('button', { name: 'Add equation', exact: true }).click();
  await expect(blocks.last()).toHaveAttribute('data-latex', /eq:extra-2/);
  await expect(page.getByRole('status')).toContainText('References resolved');
  const beforeInvalid = await jsonValue();
  await file.setInputFiles({ name: 'invalid.json', mimeType: 'application/json', buffer: Buffer.from('{"type":"doc","content":[{"type":"unknown"}]}') });
  await expect(page.locator('[data-file-message]')).toContainText('File not opened');
  expect(await jsonValue()).toEqual(beforeInvalid);
  await page.getByRole('button', { name: 'Undo', exact: true }).click();
  expect(await jsonValue()).toEqual(saved);
  await author.screenshot({ path: info.outputPath('01-reopened-equations.png') });
  await page.getByRole('region', { name: 'Equation reading' }).screenshot({ path: info.outputPath('02-reopened-reader.png') });
  const markdownEvent = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Save Markdown', exact: true }).click();
  const markdownDownload = await markdownEvent;
  const markdownPath = info.outputPath('equations.md');
  await markdownDownload.saveAs(markdownPath);
  const markdown = await readFile(markdownPath, 'utf8');
  for (const block of saved.content) if (block.type === 'math_block') expect(markdown).toContain(block.attrs.latex);
  const readerLink = reader.locator('a').first();
  const href = await readerLink.getAttribute('href');
  await readerLink.click();
  expect(new URL(page.url()).hash).toBe(href);
  await expect(reader.locator('textarea:visible')).toHaveCount(0);
  expect(errors).toEqual([]);
}
