import { expect, type Page, type TestInfo } from '@playwright/test';

export async function productWorkflowJourney(page: Page, info: TestInfo): Promise<void> {
  const pageErrors: string[] = [];
  page.on('pageerror', error => pageErrors.push(error.message));
  const capture = async (name: string) => {
    await page.evaluate(async () => {
      await document.fonts.ready;
      window.scrollTo({ top: 0, left: 0, behavior: 'instant' });
      await new Promise<void>(resolve => requestAnimationFrame(() => requestAnimationFrame(() => resolve())));
    });
    await page.screenshot({ path: info.outputPath(name), fullPage: true });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true);
  };
  await page.goto('/demos.html');
  const discovery = page.getByRole('region', { name: 'Real-world workflow demos' });
  await expect(discovery).toBeInViewport();
  await expect(discovery.getByRole('link', { name: 'Open GitLab-style issue editor' })).toBeVisible();
  await capture('gallery-discovery.png');
  await discovery.getByRole('link', { name: 'Explore product workflows' }).click();
  await expect(page).toHaveURL(/\/workflows.html$/);
  await capture('workflow-hub.png');
  await page.getByRole('link', { name: 'Try the issue editor' }).click();
  await expect(page.getByRole('textbox', { name: 'Issue description editor', exact: true })).toBeVisible();
  await page.getByRole('navigation', { name: 'Primary navigation' }).getByRole('link', { name: 'Workflows' }).click();
  await page.getByRole('link', { name: 'Try the task workspace' }).click();
  await expect(page).toHaveURL(/\/task-workflow.html$/);
  const pane = page.locator('.task-pane:not([hidden])');
  const editor = pane.getByRole('textbox', { name: 'Task description editor', exact: true });
  const tasks = page.getByRole('navigation', { name: 'Tasks', exact: true });
  const append = async (value: string) => {
    await editor.locator('p').last().click();
    await page.keyboard.press('ControlOrMeta+End');
    await page.keyboard.type(value);
  };
  await expect(editor).toContainText('short and useful');
  await append(' Launch approved.');
  await expect(editor).toContainText('Launch approved.');
  await tasks.getByRole('button', { name: 'Review the technical notes' }).click();
  await expect(editor).toContainText('Technical review');
  await append(' Verified separately.');
  await tasks.getByRole('button', { name: 'Write the launch brief' }).click();
  await expect(editor).toContainText('Launch approved.');
  await editor.click();
  await page.keyboard.press('ControlOrMeta+z');
  await expect(editor).not.toContainText('Launch approved.');
  await page.keyboard.press('ControlOrMeta+Shift+z');
  await expect(editor).toContainText('Launch approved.');
  await tasks.getByRole('button', { name: 'Review the technical notes' }).click();
  await expect(editor).toContainText('Verified separately.');
  await tasks.getByRole('button', { name: 'Write the launch brief' }).click();
  await pane.getByLabel('Due date', { exact: true }).fill('2026-09-20');
  await pane.getByLabel('Completed', { exact: true }).check();
  await expect(page.locator('.task-sidebar')).toContainText('2 of 3 completed');
  await capture('task-editor.png');
  await pane.getByRole('button', { name: 'Reader preview', exact: true }).click();
  const reader = pane.getByRole('textbox', { name: 'Task description preview', exact: true });
  await expect(reader).toHaveAttribute('contenteditable', 'false');
  await expect(reader).toContainText('Launch approved.');
  await expect(editor).not.toBeVisible();
  await capture('task-reader.png');
  await pane.getByRole('button', { name: 'Edit description', exact: true }).click();
  const downloading = page.waitForEvent('download');
  await pane.getByRole('button', { name: 'Download description', exact: true }).click();
  const download = await downloading;
  expect(download.suggestedFilename()).toBe('brief-description.md');
  const draft = info.outputPath('brief-description.md');
  await download.saveAs(draft);
  await append(' Newer unsaved change.');
  await pane.getByLabel('Open task Markdown file', { exact: true }).setInputFiles(draft);
  await expect(editor).toContainText('Launch approved.');
  await expect(editor).not.toContainText('Newer unsaved change.');
  await expect(pane.getByRole('status')).toContainText('Opened brief-description.md');
  await editor.click();
  await page.keyboard.press('ControlOrMeta+z');
  await expect(editor).toContainText('Newer unsaved change.');
  await expect(pane.getByLabel('Due date', { exact: true })).toHaveValue('2026-09-20');
  await expect(pane.getByLabel('Completed', { exact: true })).toBeChecked();
  await pane.getByLabel('Open task Markdown file', { exact: true }).setInputFiles({ name: 'too-large.md', mimeType: 'text/markdown', buffer: Buffer.alloc(2 * 1024 * 1024 + 1, 65) });
  await expect(pane.getByRole('alert')).toContainText('smaller than 2 MiB');
  await expect(editor).toContainText('Newer unsaved change.');
  await page.getByRole('button', { name: '+ Add task', exact: true }).click();
  await pane.getByLabel('Task title', { exact: true }).fill('Check the handoff');
  await append(' Ready for review.');
  await expect(tasks.getByRole('button', { name: 'Check the handoff' })).toHaveAttribute('aria-pressed', 'true');
  await tasks.getByRole('button', { name: 'Review the technical notes' }).click();
  await expect(editor).toContainText('Verified separately.');
  await tasks.getByRole('button', { name: 'Check the handoff' }).click();
  await expect(editor).toContainText('Ready for review.');
  await page.setViewportSize({ width: 390, height: 844 });
  await capture('task-mobile.png');
  await pane.getByRole('button', { name: 'Reader preview', exact: true }).click();
  await expect(reader).toContainText('Ready for review.');
  await capture('task-reader-mobile.png');
  await page.getByRole('navigation', { name: 'Primary navigation' }).getByRole('link', { name: 'Workflows' }).click();
  await capture('workflow-hub-mobile.png');
  await page.getByRole('navigation', { name: 'Primary navigation' }).getByRole('link', { name: '10 demos' }).click();
  await expect(discovery).toBeVisible();
  await capture('gallery-discovery-mobile.png');
  expect(pageErrors).toEqual([]);
}
