import { expect, type Page, type TestInfo } from '@playwright/test';

/** Public controls and native keyboard input, not calls to a hidden test editor. */
export async function vueRunbookJourney(page: Page, info: TestInfo) {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/demos/vue-runbook.html');
  const workspace = page.locator('[data-vue-runbook]');
  const editor = page.getByRole('textbox', { name: 'Vue runbook editor' });
  await expect(editor).toBeVisible();
  const inspector = workspace.locator('.demo-output pre');
  const initial = await inspector.textContent();
  const text = 'Release notes verified by the team.';
  await editor.click();
  await page.keyboard.press('Control+End');
  await page.keyboard.press('Enter');
  await page.keyboard.type(text);
  await expect(editor).toContainText(text);
  await expect(inspector).toContainText(text);
  // Backward selection must remain attached when a Vue toolbar command runs.
  for (let character = 0; character < text.length; character++) await page.keyboard.press('Shift+ArrowLeft');
  await workspace.getByRole('button', { name: 'Bold', exact: true }).click();
  await expect(editor.locator('strong')).toContainText([text]);
  const edited = await inspector.textContent();
  await workspace.getByRole('button', { name: 'Hide editor', exact: true }).click();
  await expect(editor).toHaveCount(0);
  await expect(workspace.getByRole('status')).toContainText('undo history retained');
  await expect(inspector).toHaveText(edited!);
  await workspace.getByRole('button', { name: 'Show editor', exact: true }).click();
  await expect(editor.locator('strong')).toContainText([text]);
  await workspace.getByRole('button', { name: 'Undo', exact: true }).click();
  await expect(editor.locator('strong')).toHaveCount(0);
  await expect(editor).toContainText(text);
  await workspace.getByRole('button', { name: 'Redo', exact: true }).click();
  await expect(editor.locator('strong')).toContainText([text]);
  const task = editor.getByRole('checkbox').nth(1);
  await expect(task).not.toBeChecked();
  await task.check();
  await expect(task).toBeChecked();
  const updated = await inspector.textContent();
  expect(updated).not.toBe(initial);
  await workspace.getByRole('button', { name: 'Hide editor', exact: true }).click();
  await workspace.getByRole('button', { name: 'Show editor', exact: true }).click();
  await expect(task).toBeChecked();
  await expect(inspector).toHaveText(updated!);
  expect((await workspace.locator('.demo-output').boundingBox())!.height).toBeLessThanOrEqual(760);
  await workspace.locator('.demo-surface').scrollIntoViewIfNeeded();
  const screenshot = info.outputPath('vue-edited-runbook.png');
  await page.screenshot({ path: screenshot });
  await info.attach('Vue runbook after editing and view remount', { path: screenshot, contentType: 'image/png' });
  await workspace.getByRole('button', { name: 'markdown', exact: true }).click();
  await expect(inspector).toContainText(`**${text}**`);
  await expect(inspector).toContainText('- [x] Inspect the packed npm artifact');
  // Size a table, edit it, and recover deletion through the Vue controls.
  await editor.locator('p').last().click();
  await page.keyboard.press('End');
  await workspace.getByRole('button', { name: 'Quote', exact: true }).click();
  await expect(editor.locator('blockquote')).toContainText(text);
  await workspace.getByRole('button', { name: 'Remove quote', exact: true }).click();
  await expect(editor.locator('blockquote')).toHaveCount(0);
  await workspace.getByLabel('Table rows', { exact: true }).fill('3');
  await workspace.getByLabel('Table columns', { exact: true }).fill('4');
  await workspace.getByRole('button', { name: '+ Table', exact: true }).click();
  await expect(editor.locator('table tr')).toHaveCount(3);
  await expect(editor.locator('table th, table td')).toHaveCount(12);
  await editor.locator('table th').first().click();
  await page.keyboard.type('Release owner');
  await workspace.locator('summary').filter({ hasText: 'Table options' }).click();
  await workspace.getByRole('button', { name: 'Add row below', exact: true }).click();
  await expect(editor.locator('table tr')).toHaveCount(4);
  await workspace.getByRole('button', { name: 'Add column right', exact: true }).click();
  await expect(editor.locator('table th, table td')).toHaveCount(20);
  await workspace.getByRole('button', { name: 'Delete entire table', exact: true }).click();
  await expect(editor.locator('table')).toHaveCount(0);
  await workspace.getByRole('button', { name: 'Undo', exact: true }).click();
  await expect(editor.locator('table th, table td')).toHaveCount(20);
  await expect(editor.locator('table')).toContainText('Release owner');
  await editor.locator('table').scrollIntoViewIfNeeded();
  const tableShot = info.outputPath('vue-table-controls.png');
  await page.screenshot({ path: tableShot });
  await info.attach('Vue table recovery', { path: tableShot, contentType: 'image/png' });
  // Real page navigation destroys the app and a new visit gets a new editor.
  await page.getByRole('navigation', { name: 'Primary navigation' }).getByRole('link', { name: '10 demos' }).click();
  await expect(page).toHaveURL(/demos\.html$/);
  await page.goto('/demos/vue-runbook.html');
  await expect(editor).toBeVisible();
  await expect(editor).not.toContainText(text);
  expect(errors).toEqual([]);
}
