import { expect, test } from '@playwright/test';
import { mathReferenceSamples } from '../../examples/react-app/src/math-reference-samples';

test('human real-renderer journey: edit a typeset equation, inspect a published failure, and recover', async ({ page }, info) => {
  await page.goto('/math-renderer.html');
  await page.evaluate(() => document.fonts.ready);
  const math = page.locator('[data-fountain-math="block"]');
  const source = page.getByLabel('Edit math source', { exact: true });
  await math.scrollIntoViewIfNeeded();
  await expect(math.locator('.katex')).toBeVisible();
  await page.screenshot({ path: info.outputPath('01-real-aligned-typesetting.png') });
  await source.focus();
  await source.press('Control+Home');
  await source.press('ArrowDown');
  await source.press('ArrowDown');
  await source.press('End');
  await source.press('Shift+Home');
  await page.keyboard.type('x_{n+1} &= 3x_n');
  await expect(math.locator('annotation')).toHaveText(mathReferenceSamples[0].source.replace('2x_n', '3x_n'));
  await source.press('Control+Enter');
  await page.getByRole('button', { name: 'Undo', exact: true }).click();
  await expect(math.locator('annotation')).toHaveText(mathReferenceSamples[0].source);
  await page.getByRole('button', { name: 'Redo', exact: true }).click();
  await expect(math.locator('annotation')).toHaveText(mathReferenceSamples[0].source.replace('2x_n', '3x_n'));
  await page.getByLabel('Reference sample').selectOption('2');
  await page.getByRole('button', { name: 'Load sample (replaces editor)' }).click();
  await expect(page.getByRole('status')).toContainText('Source fallback');
  await expect(source).toHaveValue(mathReferenceSamples[2].source);
  await expect(math.locator('.katex')).toHaveCount(0);
  await math.scrollIntoViewIfNeeded();
  await page.screenshot({ path: info.outputPath('02-published-equation-explicit-fallback.png') });
  await source.fill('\\int_0^1 x^2\\,dx = \\frac{1}{3}');
  await expect(math.locator('.katex')).toBeVisible();
  await expect(page.getByRole('status')).toContainText('Typeset view ready');
  await page.getByText('Markdown export', { exact: true }).click();
  await expect(page.locator('details').last()).toContainText('\\int_0^1 x^2\\,dx = \\frac{1}{3}');
  await math.scrollIntoViewIfNeeded();
  await page.screenshot({ path: info.outputPath('03-rendering-recovers-after-edit.png') });
  await page.setViewportSize({ width: 390, height: 844 });
  await math.scrollIntoViewIfNeeded();
  await expect(math.locator('.katex')).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
  await page.screenshot({ path: info.outputPath('04-narrow-screen-real-formula.png') });
});
