import type {
  AIGeneratedMediaAsset,
  AIGeneratedMediaCommitter,
} from '../ai/generated-media';
import type { Editor } from '../core';
import {
  insertAssetFile,
  insertImageFile,
  type AssetUploadHandler,
  type InsertAssetFileOptions,
  type InsertImageFileOptions,
  type ImageUploadHandler,
} from './media';

export interface InsertAIGeneratedMediaOptions {
  /** Required for generated images; owns validation, persistence, and the final URL. */
  readonly imageUpload?: ImageUploadHandler;
  /** Required for generated audio, video, and files; owns persistence and the final URL. */
  readonly assetUpload?: AssetUploadHandler;
  readonly image?: Omit<InsertImageFileOptions, 'upload' | 'signal' | 'onStatusChange'>;
  readonly asset?: Omit<InsertAssetFileOptions, 'upload' | 'kind' | 'signal' | 'onStatusChange'>;
}

/** Creates a browser File from a reviewed candidate without fetching a provider URL. */
export function aiGeneratedMediaFile(asset: AIGeneratedMediaAsset): File {
  if (typeof File === 'undefined') throw new Error('Generated media upload requires a browser File implementation.');
  return new File([asset.bytes.slice()], asset.name, { type: asset.mimeType });
}

/**
 * Sends reviewed generated bytes through the same host-owned upload and mapped
 * insertion path used by a human-selected local file.
 */
export async function insertAIGeneratedMedia(
  editor: Editor,
  asset: AIGeneratedMediaAsset,
  context: { readonly signal: AbortSignal; reportProgress(progress: number): void },
  options: InsertAIGeneratedMediaOptions,
): Promise<boolean> {
  const file = aiGeneratedMediaFile(asset);
  if (asset.kind === 'image') {
    if (!options.imageUpload) throw new TypeError('Generated images require a host image upload handler.');
    return insertImageFile(editor, file, {
      ...options.image,
      upload: options.imageUpload,
      signal: context.signal,
      alt: options.image?.alt ?? asset.alt ?? asset.title ?? asset.name.replace(/\.[^.]+$/, ''),
      title: options.image?.title ?? asset.title ?? '',
      caption: options.image?.caption ?? asset.caption ?? '',
      onStatusChange: (snapshot) => context.reportProgress(snapshot.progress),
    });
  }
  if (!options.assetUpload) throw new TypeError('Generated audio, video, and files require a host asset upload handler.');
  return insertAssetFile(editor, file, {
    ...options.asset,
    kind: asset.kind,
    upload: options.assetUpload,
    signal: context.signal,
    attributes: {
      ...options.asset?.attributes,
      ...(asset.title ? { title: asset.title } : {}),
      ...(asset.caption ? { caption: asset.caption } : {}),
      ...(asset.kind === 'file' && asset.caption ? { description: asset.caption } : {}),
    },
    onStatusChange: (snapshot) => context.reportProgress(snapshot.progress),
  });
}

/** Binds an editor and its host upload adapters for `controller.accept`. */
export function createAIGeneratedMediaCommitter(
  editor: Editor,
  options: InsertAIGeneratedMediaOptions,
): AIGeneratedMediaCommitter {
  return (asset, context) => insertAIGeneratedMedia(editor, asset, context, options);
}
