export const MAX_AI_MEDIA_PROMPT_LENGTH = 100_000;
export const MAX_AI_MEDIA_ASSETS = 8;
export const DEFAULT_MAX_AI_MEDIA_ASSET_BYTES = 20 * 1024 * 1024;
export const DEFAULT_MAX_AI_MEDIA_TOTAL_BYTES = 50 * 1024 * 1024;

export type AIGeneratedMediaKind = 'image' | 'audio' | 'video' | 'file';
export type AIGeneratedMediaAssetStatus = 'pending' | 'accepted' | 'rejected';

export interface AIGeneratedMediaRequestOptions {
  readonly kind: AIGeneratedMediaKind;
  readonly prompt: string;
  /** Defaults to one and is capped at eight. */
  readonly count?: number;
  readonly aspectRatio?: string;
  readonly durationSeconds?: number;
  readonly metadata?: Readonly<Record<string, unknown>>;
}

/** Complete, inspectable payload sent to the host's generation adapter. */
export interface AIGeneratedMediaRequest {
  readonly id: string;
  readonly kind: AIGeneratedMediaKind;
  readonly prompt: string;
  readonly count: number;
  readonly aspectRatio?: string;
  readonly durationSeconds?: number;
  readonly metadata?: Readonly<Record<string, unknown>>;
  readonly privacy: {
    readonly includesDocumentContent: false;
    readonly includesReferenceAssets: false;
  };
}

export interface AIGeneratedMediaCandidate {
  readonly id: string;
  readonly kind: AIGeneratedMediaKind;
  readonly name: string;
  readonly mimeType: string;
  /** Raw generated bytes. Fountain copies them before exposing a review asset. */
  readonly bytes: Uint8Array;
  readonly alt?: string;
  readonly title?: string;
  readonly caption?: string;
  readonly metadata?: Readonly<Record<string, unknown>>;
}

export interface AIGeneratedMediaResult {
  readonly assets: readonly AIGeneratedMediaCandidate[];
  readonly model?: string;
  readonly provider?: string;
  readonly revisedPrompt?: string;
  readonly metadata?: Readonly<Record<string, unknown>>;
}

export interface AIGeneratedMediaAdapterContext {
  readonly signal: AbortSignal;
  /** Generation progress, not upload progress. */
  reportProgress(progress: number): void;
}

export interface AIGeneratedMediaAdapter {
  generate(
    request: AIGeneratedMediaRequest,
    context: AIGeneratedMediaAdapterContext,
  ): Promise<AIGeneratedMediaResult>;
}

export interface AIGeneratedMediaAsset extends Omit<AIGeneratedMediaCandidate, 'bytes'> {
  readonly bytes: Uint8Array;
  readonly status: AIGeneratedMediaAssetStatus;
  readonly requestId: string;
  readonly model?: string;
  readonly provider?: string;
  readonly revisedPrompt?: string;
  /** Provider-owned metadata for the generation as a whole, kept separate from per-asset metadata. */
  readonly generationMetadata?: Readonly<Record<string, unknown>>;
}

export interface AIGeneratedMediaAcceptContext {
  readonly signal: AbortSignal;
  /** Reports persistence/upload progress independently from generation. */
  reportProgress(progress: number): void;
}

export type AIGeneratedMediaCommitter = (
  asset: AIGeneratedMediaAsset,
  context: AIGeneratedMediaAcceptContext,
) => boolean | Promise<boolean>;

export interface AIGeneratedMediaDecisionEvent {
  readonly requestId: string;
  readonly assetId: string;
  readonly decision: 'accepted' | 'rejected';
  readonly timestamp: number;
}

export interface AIGeneratedMediaSnapshot {
  readonly status: 'idle' | 'generating' | 'review' | 'accepting' | 'error';
  readonly request?: AIGeneratedMediaRequest;
  readonly lastRequest?: AIGeneratedMediaRequest;
  readonly assets: readonly AIGeneratedMediaAsset[];
  readonly activeAssetId?: string;
  readonly generationProgress: number;
  readonly uploadProgress: number;
  readonly error?: string;
}

export interface AIGeneratedMediaControllerOptions {
  readonly adapter: AIGeneratedMediaAdapter;
  readonly maxAssetBytes?: number;
  readonly maxTotalBytes?: number;
  readonly idFactory?: (kind: 'request') => string;
  readonly now?: () => number;
}

const MIME_BY_KIND: Readonly<Record<AIGeneratedMediaKind, readonly RegExp[]>> = Object.freeze({
  image: Object.freeze([/^image\/(?:png|jpeg|webp|gif|avif)$/i]),
  audio: Object.freeze([/^audio\/(?:mpeg|mp4|ogg|wav|webm|aac|flac)$/i]),
  video: Object.freeze([/^video\/(?:mp4|ogg|webm|quicktime)$/i]),
  file: Object.freeze([/^[a-z0-9][a-z0-9!#$&^_.+-]*\/[a-z0-9][a-z0-9!#$&^_.+-]*$/i]),
});

let requestCounter = 0;

function generatedId(): string {
  requestCounter += 1;
  return `media-request-${Date.now().toString(36)}-${requestCounter.toString(36)}`;
}

function validId(value: unknown): value is string {
  return typeof value === 'string' && value.length > 0 && value.length <= 240 && /^[\w.:@/-]+$/.test(value);
}

function boundedText(value: unknown, label: string, maximum: number, trim = false): string {
  if (typeof value !== 'string' || !value.trim() || value.length > maximum || value.includes('\0')) {
    throw new TypeError(`${label} must be bounded, non-empty text.`);
  }
  return trim ? value.trim() : value;
}

function optionalText(value: unknown, label: string, maximum: number): string | undefined {
  if (value === undefined) return undefined;
  return boundedText(value, label, maximum, true);
}

function jsonObject(value: unknown, label: string): Readonly<Record<string, unknown>> | undefined {
  if (value === undefined) return undefined;
  if (!value || typeof value !== 'object' || Array.isArray(value)) throw new TypeError(`${label} must be an object.`);
  let encoded: string | undefined;
  try { encoded = JSON.stringify(value); } catch { throw new TypeError(`${label} must be JSON serializable.`); }
  if (encoded === undefined || encoded.length > 100_000 || encoded.includes('\0')) throw new RangeError(`${label} exceeds the safety limit.`);
  return deepFreeze(JSON.parse(encoded) as Record<string, unknown>);
}

function deepFreeze<T>(value: T): T {
  if (value && typeof value === 'object' && !ArrayBuffer.isView(value) && !Object.isFrozen(value)) {
    Object.freeze(value);
    Object.values(value as Record<string, unknown>).forEach(deepFreeze);
  }
  return value;
}

function checkedLimit(value: number | undefined, fallback: number, label: string): number {
  const resolved = value ?? fallback;
  if (!Number.isSafeInteger(resolved) || resolved < 1 || resolved > 1024 * 1024 * 1024) {
    throw new RangeError(`${label} must be an integer from 1 byte through 1 GiB.`);
  }
  return resolved;
}

function checkedProgress(progress: number, label: string): number {
  if (!Number.isFinite(progress) || progress < 0 || progress > 1) throw new RangeError(`${label} must be between 0 and 1.`);
  return progress;
}

function abortError(message: string): Error {
  const error = new Error(message);
  error.name = 'AbortError';
  return error;
}

function normalizeRequest(
  options: AIGeneratedMediaRequestOptions,
  idFactory: AIGeneratedMediaControllerOptions['idFactory'],
): AIGeneratedMediaRequest {
  if (!options || !['image', 'audio', 'video', 'file'].includes(options.kind)) {
    throw new TypeError('Generated media kind must be image, audio, video, or file.');
  }
  const count = options.count ?? 1;
  if (!Number.isSafeInteger(count) || count < 1 || count > MAX_AI_MEDIA_ASSETS) {
    throw new RangeError(`Generated media count must be from 1 through ${MAX_AI_MEDIA_ASSETS}.`);
  }
  if (options.durationSeconds !== undefined
    && (!Number.isFinite(options.durationSeconds) || options.durationSeconds <= 0 || options.durationSeconds > 86_400)) {
    throw new RangeError('Generated media duration must be greater than zero and no more than 24 hours.');
  }
  const id = idFactory?.('request') ?? generatedId();
  if (!validId(id)) throw new TypeError('Invalid generated-media request id.');
  const aspectRatio = optionalText(options.aspectRatio, 'Generated media aspect ratio', 100);
  const metadata = jsonObject(options.metadata, 'Generated media request metadata');
  return Object.freeze({
    id,
    kind: options.kind,
    prompt: boundedText(options.prompt, 'Generated media prompt', MAX_AI_MEDIA_PROMPT_LENGTH),
    count,
    ...(aspectRatio ? { aspectRatio } : {}),
    ...(options.durationSeconds !== undefined ? { durationSeconds: options.durationSeconds } : {}),
    ...(metadata ? { metadata } : {}),
    privacy: Object.freeze({ includesDocumentContent: false as const, includesReferenceAssets: false as const }),
  });
}

function normalizedAsset(
  candidate: AIGeneratedMediaCandidate,
  request: AIGeneratedMediaRequest,
  result: AIGeneratedMediaResult,
  maxAssetBytes: number,
): AIGeneratedMediaAsset {
  if (!candidate || !validId(candidate.id) || candidate.kind !== request.kind) {
    throw new TypeError('The generation adapter returned an invalid or mismatched asset.');
  }
  const mimeType = boundedText(candidate.mimeType, 'Generated media MIME type', 200, true).toLowerCase();
  if (!MIME_BY_KIND[candidate.kind].some((pattern) => pattern.test(mimeType))) {
    throw new TypeError(`Generated ${candidate.kind} MIME type is not permitted: ${mimeType}`);
  }
  if (!(candidate.bytes instanceof Uint8Array) || candidate.bytes.byteLength < 1 || candidate.bytes.byteLength > maxAssetBytes) {
    throw new RangeError(`Generated media bytes must contain 1 through ${maxAssetBytes} bytes.`);
  }
  const metadata = jsonObject(candidate.metadata, 'Generated media asset metadata');
  const generationMetadata = jsonObject(result.metadata, 'Generated media result metadata');
  return Object.freeze({
    id: candidate.id,
    kind: candidate.kind,
    name: boundedText(candidate.name, 'Generated media file name', 500, true),
    mimeType,
    bytes: candidate.bytes.slice(),
    status: 'pending' as const,
    requestId: request.id,
    ...(optionalText(candidate.alt, 'Generated media alt text', 10_000) ? { alt: candidate.alt!.trim() } : {}),
    ...(optionalText(candidate.title, 'Generated media title', 10_000) ? { title: candidate.title!.trim() } : {}),
    ...(optionalText(candidate.caption, 'Generated media caption', 100_000) ? { caption: candidate.caption!.trim() } : {}),
    ...(metadata ? { metadata } : {}),
    ...(optionalText(result.model, 'Generated media model', 500) ? { model: result.model!.trim() } : {}),
    ...(optionalText(result.provider, 'Generated media provider', 500) ? { provider: result.provider!.trim() } : {}),
    ...(optionalText(result.revisedPrompt, 'Generated media revised prompt', MAX_AI_MEDIA_PROMPT_LENGTH)
      ? { revisedPrompt: result.revisedPrompt } : {}),
    ...(generationMetadata ? { generationMetadata } : {}),
  });
}

function publicAsset(asset: AIGeneratedMediaAsset): AIGeneratedMediaAsset {
  return Object.freeze({ ...asset, bytes: asset.bytes.slice() });
}

export class AIGeneratedMediaController {
  private readonly listeners = new Set<() => void>();
  private readonly maxAssetBytes: number;
  private readonly maxTotalBytes: number;
  private readonly now: () => number;
  private assets: readonly AIGeneratedMediaAsset[] = Object.freeze([]);
  private snapshot: AIGeneratedMediaSnapshot = Object.freeze({
    status: 'idle', assets: Object.freeze([]), generationProgress: 0, uploadProgress: 0,
  });
  private activeAbort?: AbortController;

  constructor(private readonly options: AIGeneratedMediaControllerOptions) {
    if (!options?.adapter || typeof options.adapter.generate !== 'function') {
      throw new TypeError('Generated media requires a host generation adapter.');
    }
    this.maxAssetBytes = checkedLimit(options.maxAssetBytes, DEFAULT_MAX_AI_MEDIA_ASSET_BYTES, 'Per-asset limit');
    this.maxTotalBytes = checkedLimit(options.maxTotalBytes, DEFAULT_MAX_AI_MEDIA_TOTAL_BYTES, 'Total asset limit');
    this.now = options.now ?? Date.now;
  }

  getSnapshot = (): AIGeneratedMediaSnapshot => this.snapshot;

  subscribe = (listener: () => void): (() => void) => {
    this.listeners.add(listener);
    return () => this.listeners.delete(listener);
  };

  inspectRequest(options: AIGeneratedMediaRequestOptions): AIGeneratedMediaRequest {
    return normalizeRequest(options, this.options.idFactory);
  }

  async generate(options: AIGeneratedMediaRequestOptions): Promise<readonly AIGeneratedMediaAsset[]> {
    if (this.activeAbort) throw new Error('A generated-media operation is already active.');
    const request = this.inspectRequest(options);
    const abort = new AbortController();
    this.activeAbort = abort;
    this.assets = Object.freeze([]);
    this.publish('generating', { request, lastRequest: request, generationProgress: 0, uploadProgress: 0 });
    try {
      const result = await this.options.adapter.generate(request, {
        signal: abort.signal,
        reportProgress: (progress) => {
          if (this.activeAbort !== abort) return;
          this.publish('generating', { request, lastRequest: request, generationProgress: checkedProgress(progress, 'Generation progress'), uploadProgress: 0 });
        },
      });
      if (abort.signal.aborted || this.activeAbort !== abort) throw abortError('Generated media request was cancelled.');
      if (!result || !Array.isArray(result.assets) || result.assets.length < 1 || result.assets.length > request.count) {
        throw new RangeError('The generation adapter returned an invalid number of assets.');
      }
      const ids = new Set<string>();
      const assets = result.assets.map((candidate) => {
        const asset = normalizedAsset(candidate, request, result, this.maxAssetBytes);
        if (ids.has(asset.id)) throw new TypeError('Generated media asset ids must be unique.');
        ids.add(asset.id);
        return asset;
      });
      const totalBytes = assets.reduce((total, asset) => total + asset.bytes.byteLength, 0);
      if (totalBytes > this.maxTotalBytes) throw new RangeError(`Generated media exceeded the ${this.maxTotalBytes}-byte total limit.`);
      this.assets = Object.freeze(assets);
      this.activeAbort = undefined;
      this.publish('review', { lastRequest: request, generationProgress: 1, uploadProgress: 0 });
      return Object.freeze(assets.map(publicAsset));
    } catch (error) {
      if (this.activeAbort === abort) this.activeAbort = undefined;
      const cancelled = abort.signal.aborted || (error instanceof Error && error.name === 'AbortError');
      this.publish(cancelled ? 'idle' : 'error', {
        lastRequest: request,
        generationProgress: this.snapshot.generationProgress,
        uploadProgress: 0,
        ...(!cancelled ? { error: error instanceof Error ? error.message : 'Generated media request failed.' } : {}),
      });
      throw error;
    }
  }

  async accept(assetOrId: AIGeneratedMediaAsset | string, commit: AIGeneratedMediaCommitter): Promise<AIGeneratedMediaDecisionEvent> {
    if (this.activeAbort) throw new Error('A generated-media operation is already active.');
    if (typeof commit !== 'function') throw new TypeError('Generated media acceptance requires an upload committer.');
    const asset = this.pendingAsset(assetOrId);
    const abort = new AbortController();
    this.activeAbort = abort;
    this.publish('accepting', { activeAssetId: asset.id, generationProgress: 1, uploadProgress: 0 });
    try {
      const accepted = await commit(publicAsset(asset), {
        signal: abort.signal,
        reportProgress: (progress) => {
          if (this.activeAbort !== abort) return;
          this.publish('accepting', { activeAssetId: asset.id, generationProgress: 1, uploadProgress: checkedProgress(progress, 'Upload progress') });
        },
      });
      if (abort.signal.aborted || this.activeAbort !== abort) throw abortError('Generated media upload was cancelled.');
      if (accepted !== true) throw new Error('The generated media was not inserted.');
      this.replaceAsset(asset.id, { ...asset, status: 'accepted' });
      this.activeAbort = undefined;
      this.publish('review', { generationProgress: 1, uploadProgress: 1 });
      return Object.freeze({ requestId: asset.requestId, assetId: asset.id, decision: 'accepted', timestamp: this.now() });
    } catch (error) {
      if (this.activeAbort === abort) this.activeAbort = undefined;
      const cancelled = abort.signal.aborted || (error instanceof Error && error.name === 'AbortError');
      this.publish(cancelled ? 'review' : 'error', {
        generationProgress: 1,
        uploadProgress: this.snapshot.uploadProgress,
        ...(!cancelled ? { error: error instanceof Error ? error.message : 'Generated media upload failed.' } : {}),
      });
      throw error;
    }
  }

  reject(assetOrId: AIGeneratedMediaAsset | string): AIGeneratedMediaDecisionEvent {
    if (this.activeAbort) throw new Error('A generated-media operation is already active.');
    const asset = this.pendingAsset(assetOrId);
    this.replaceAsset(asset.id, { ...asset, status: 'rejected' });
    this.publish('review', { generationProgress: 1, uploadProgress: 0 });
    return Object.freeze({ requestId: asset.requestId, assetId: asset.id, decision: 'rejected', timestamp: this.now() });
  }

  cancel(): void {
    this.activeAbort?.abort();
  }

  clear(): void {
    if (this.activeAbort) throw new Error('Cannot clear generated media while an operation is active.');
    this.assets = Object.freeze([]);
    this.publish('idle', { generationProgress: 0, uploadProgress: 0 });
  }

  private pendingAsset(assetOrId: AIGeneratedMediaAsset | string): AIGeneratedMediaAsset {
    const id = typeof assetOrId === 'string' ? assetOrId : assetOrId.id;
    const asset = this.assets.find((candidate) => candidate.id === id);
    if (!asset) throw new Error(`Unknown generated media asset: ${id}`);
    if (asset.status !== 'pending') throw new Error(`Generated media asset ${id} is already ${asset.status}.`);
    return asset;
  }

  private replaceAsset(id: string, replacement: AIGeneratedMediaAsset): void {
    this.assets = Object.freeze(this.assets.map((asset) => asset.id === id ? Object.freeze(replacement) : asset));
  }

  private publish(status: AIGeneratedMediaSnapshot['status'], change: Omit<Partial<AIGeneratedMediaSnapshot>, 'status' | 'assets'>): void {
    this.snapshot = Object.freeze({
      status,
      assets: Object.freeze(this.assets.map(publicAsset)),
      generationProgress: change.generationProgress ?? this.snapshot.generationProgress,
      uploadProgress: change.uploadProgress ?? this.snapshot.uploadProgress,
      ...(change.request ? { request: change.request } : {}),
      ...(change.lastRequest ?? this.snapshot.lastRequest ? { lastRequest: change.lastRequest ?? this.snapshot.lastRequest } : {}),
      ...(change.activeAssetId ? { activeAssetId: change.activeAssetId } : {}),
      ...(change.error ? { error: change.error } : {}),
    });
    this.listeners.forEach((listener) => listener());
  }
}

export function createAIGeneratedMediaAdapter(
  generate: AIGeneratedMediaAdapter['generate'],
): AIGeneratedMediaAdapter {
  if (typeof generate !== 'function') throw new TypeError('Generated media adapter must be a function.');
  return Object.freeze({ generate });
}
